$projectName = "azure-functions-stock-ticker"
$resourceGroup = "$projectName-rg";
$location = "eastus";
$appServicePlan = "$projectName-sp"
$appService = "$projectName-webapp"
$storageAccountName = "afststorage"
$functionAppName = "afstfunctionapp"
$azureCosmosAccountName = "$projectName-cosmos"
$azureCosmosDatabase = "$projectName-cosmos-databse"
$container = "stockprice"
$partitionKey ="/id"